@AgendaApi.API_HostAddress = http://localhost:5123

GET {{AgendaApi.API_HostAddress}}/weatherforecast/
Accept: application/json

###

###

POST {{AgendaApi.API_HostAddress}}/legalentity
Content-Type: application/json

{
  "name": "teste 11111",
  "email": "string@email.com",
  "password": "string123",
  "phoneNumber": "27999995775",
  "address": "string",
  "cnpj": "string",
  "socialName": "string"
}

###

POST {{AgendaApi.API_HostAddress}}/legalentity
Content-Type: application/json

{
  //CreateLegalEntityRequest
}

###
